// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqzfxcxKpr-RjOSe4dwT_04BuF3cHnP44',
    appId: '1:701034279451:web:a7c6f4db468bf14dce3ebe',
    messagingSenderId: '701034279451',
    projectId: 'gbsheet',
    authDomain: 'gbsheet.firebaseapp.com',
    storageBucket: 'gbsheet.appspot.com',
    measurementId: 'G-YQEK9K1JGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfgXkASJ6hpc4fz4867nPeG-yiIbMoF2Y',
    appId: '1:701034279451:android:d71de4be7ce533bece3ebe',
    messagingSenderId: '701034279451',
    projectId: 'gbsheet',
    storageBucket: 'gbsheet.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3UfZsrfvLQICslIP5UL5r5C1XG7Al2_U',
    appId: '1:701034279451:ios:314d0d6554114537ce3ebe',
    messagingSenderId: '701034279451',
    projectId: 'gbsheet',
    storageBucket: 'gbsheet.appspot.com',
    iosBundleId: 'com.arrijal.gbsheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3UfZsrfvLQICslIP5UL5r5C1XG7Al2_U',
    appId: '1:701034279451:ios:314d0d6554114537ce3ebe',
    messagingSenderId: '701034279451',
    projectId: 'gbsheet',
    storageBucket: 'gbsheet.appspot.com',
    iosBundleId: 'com.arrijal.gbsheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqzfxcxKpr-RjOSe4dwT_04BuF3cHnP44',
    appId: '1:701034279451:web:9e4bedb729c5414fce3ebe',
    messagingSenderId: '701034279451',
    projectId: 'gbsheet',
    authDomain: 'gbsheet.firebaseapp.com',
    storageBucket: 'gbsheet.appspot.com',
    measurementId: 'G-DPRN7FLF2N',
  );
}
